import React from 'react';
import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export default function Terms() {
  return (
    <>
      <Head><title>Terms & Conditions — Intellorium Business School</title></Head>
      <Navbar />
      <div className="min-h-screen bg-hero-gradient pt-24 pb-16">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="section-title mb-4">Terms & <span className="text-orange">Conditions</span></h1>
          <div className="card-dark space-y-6 text-white/60 font-inter text-sm leading-relaxed">
            <section>
              <h2 className="text-white font-semibold font-poppins text-base mb-2">1. Enrollment Agreement</h2>
              <p>By enrolling in Intellorium Business School, you agree to commit to the full 12-month Practical MBA program. The program fee of PKR 125,000 is due upon acceptance. Additionally, a 15% service fee applies to all revenue generated by your business during the program period.</p>
            </section>
            <section>
              <h2 className="text-white font-semibold font-poppins text-base mb-2">2. Service Fee Terms</h2>
              <p>The 15% service fee is calculated on monthly gross revenue reported through the Intellorium platform. This fee applies for the duration of the 12-month program only. Accurate revenue reporting is mandatory and subject to audit.</p>
            </section>
            <section>
              <h2 className="text-white font-semibold font-poppins text-base mb-2">3. Refund Policy</h2>
              <p>You may request a full refund within 5 days of payment. After 5 days, fees are non-refundable unless Intellorium cannot fulfill its program obligations. Please review our Refund Policy for complete details.</p>
            </section>
            <section>
              <h2 className="text-white font-semibold font-poppins text-base mb-2">4. Code of Conduct</h2>
              <p>Students are expected to maintain professional conduct, attend all required sessions, complete assignments, and contribute positively to the cohort community. Intellorium reserves the right to dismiss students for misconduct without refund.</p>
            </section>
            <section>
              <h2 className="text-white font-semibold font-poppins text-base mb-2">5. Intellectual Property</h2>
              <p>All business ideas, innovations, and ventures developed during the program remain the intellectual property of the student. Intellorium does not claim ownership of student business ideas.</p>
            </section>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
